### ISSUE TITLE
增强 更多LOGO匹配显示

### ISSUE THREAD

**Issue by eveloki** [SolidFaker/ohtotptoken#12]
有现成的API可用 比如 https://logo.clearbit.com/clearbit.com
文档来自https://clearbit.com/blog/logo
我们需要讨论下实现的具体细节 以及缓存LOGO的可行性
在线匹配LOGO有很多优势 我觉得这是对静态图标库的一个有效补充
另外从法律上来说 不以商业目的使用其他公司logo是没有风险的，比如微软验证器app就会自动抓取显示logo

**Comment by lsxuan12138** [comment]
理论上，在线匹配应该可行，但是个人感觉匹配规则不太好搞。这个api要求的参数是domain，比如github.com 但是扫码得到的issuer一般就是Github，除非有人去维护issuer对应的domain是什么。或者更换其他的匹配方式（但是我还想不到用什么方式）。

**Comment by lsxuan12138** [comment]
不过，刚发现，目前的方法也是有上面这个问题，比如jetbrains的扫码得到的issuer为'JetBrains Account'，但是匹配的时候用的是jetbrains

**Comment by eveloki** [comment]
可以尝试取第一个单词然后小写搜索再次匹配

**Comment by eveloki** [comment]
一个可行的方案是https://docs.logo.dev/introduction 入参可以直接是品牌名称 比如huawei 虽然是免费但是需要注册token 当然有很多方法可以保证token安全 比如编译环境变量

**Comment by qicfan** [comment]
可以参考https://github.com/beemdevelopment/Aegis，直接利用Aegis的图标库即可，让用户导入压缩包就行。

另外，这个类型的APP最好不要请求网络权限，所以读取在线图片不可取。

**Comment by eveloki** [comment]
收到，但是网络权限是接入标准化隐私声明的必要条件（最起码根据华为文档来说是这样的）因为要展示隐私声明和用户协议 这是上架的必须要求 这个我再次确认下是否必须要联网权限


---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2024年11月13日 12:31 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***>***@***.***> |
| 主题 | Re: [SolidFaker/ohtotptoken] 增强 更多LOGO匹配显示 (Issue #12) |

可以参考https://github.com/beemdevelopment/Aegis，直接利用Aegis的图标库即可，让用户导入压缩包就行。

另外，这个类型的APP最好不要请求网络权限，所以读取在线图片不可取。

**Comment by eveloki** [comment]
> 可以参考 https://github.com/beemdevelopment/Aegis
> 
> 直接利用Aegis的图标库即可，让用户导入压缩包就行。
> 
> 另外，这个类型的APP最好不要请求网络权限，所以读取在线图片不可取。

上架审核要求必须要展示隐私连接需要使用web组件
https://developer.huawei.com/consumer/cn/doc/harmonyos-references-V5/ts-basic-components-web-V5
文档显示必须要申请网络权限
ohos.permission.INTERNET


另外上架要求隐私和用户协议必须是在线的URL
参照文档为 https://developer.huawei.com/consumer/cn/doc/app/agc-help-harmonyos-useprivacystatement-0000001709322502

但是按照标准化隐私托管声明的开发文档 没有要求网络权限
https://developer.huawei.com/consumer/cn/doc/harmonyos-guides-V5/store-privacy-V5#section6348454124618
理论上可以使用弹出方式也就是打开外置浏览器的方式显示用户协议和隐私协议

这个我晚上研究下 这个确实 这个app确实不应该申请联网权限 感谢您的反馈

**Comment by eveloki** [comment]
@qicfan 您好 我与@SolidFaker 刚刚讨论了权限问题 因为本app支持forti（这也是本项目的核心需求），token需要连接验证服务器，所以网络权限是必须的，因为这个是基础权限，就跟多设备协同权限一样 可以去设置里面关闭
相关文档在https://www.fortinet.com/cn/products/identity-access-management/fortitoken
所以您的诉求暂不考虑实施
