### ISSUE TITLE
请问是否可以上线一个直接输入steam guard 导入steam令牌的功能

### ISSUE THREAD

**Issue by q177** [SolidFaker/ohtotptoken#26]
ohtotptoken中 Feature里导入的方法具有一定门槛，对于小白可能有点难，详情可以参考watt toolkit，使用watt toolkit 导入令牌是否为一个更简单的方法？请问是否可以上线一个直接输入steam guard 导入steam令牌的功能？

**Comment by SolidFaker** [comment]
watt toolkit和steam guard我之前没有使用，待我研究研究后续版本更新可以加入。

**Comment by q177** [comment]
额watt toolkit 确实是一个工具，但我说的steamguard是steam身份验证器的完整数据，包含13个键值对，我意思是直接通过输入完整数据来导入令牌，作为一个小小的建议

**Comment by q177** [comment]
![11111](https://github.com/user-attachments/assets/f5d9bfa1-55b1-43fc-9c50-6237090c0cbc)
类似这种

**Comment by SolidFaker** [comment]
> ![11111](https://private-user-images.githubusercontent.com/57666436/386920537-f5d9bfa1-55b1-43fc-9c50-6237090c0cbc.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzE4MjIyNDgsIm5iZiI6MTczMTgyMTk0OCwicGF0aCI6Ii81NzY2NjQzNi8zODY5MjA1MzctZjVkOWJmYTEtNTViMS00M2ZjLTljNTAtNjIzNzA5MGMwY2JjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTE3VDA1MzkwOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTRhMDYxMzFmYjgzYzI2MWI3M2E0ODkyYzc1ZGRhZjUwOTY3NzlmMGU5MzM0MGFiYWMxNjYzODA1OTM0OTE3MDEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.Rlg8npNFC3iCNaeBxFAGEKnaUvwrcoBZVm3o3J4Ixcg) 类似这种

看起来这个maFiles是一个json文件，应当可以比较方便的导入

**Comment by SolidFaker** [comment]
加入了从maFile导入的选项
![image](https://github.com/user-attachments/assets/05a90a95-78ad-4bc7-96f1-58f1d8276987)

**Comment by q177** [comment]
太赞了！非常感谢
